# This file provides details about each environment in the game.
#
# This is used as to generate the documentation related to environments.
# This provides a central place for this information allowing us to ensure
# diversity among the environments.
#
# For each environment include the following data:
#   name: Short but descriptive name of the environment.
#   color_scheme: Short description of the main colors that appear in the
#     environment. Use Title Case.
#   music_theme: The type or genera of music.
#   description: |
#     Detailed description that describes the environment. Include information
#     about how the grid, marks, and background look. Describe sound effects
#     and animations. This includes what happens when a mark is placed, when
#     the mouse hovers over an open or closed spot, or when the user tries to
#     select a spot that has already been taken.
#
#     This can be multiple lines long and contain reStructuredText markup if
#     needed.
#   variants: (optional) List of slight variations of the environment. For
#     example, alternate background images or mark colors.
#   concept_art: (optional) Path to the concept art image excluding the file ext.

- name: Notebook Paper and Pencil
  color_scheme: Dark graphite on white or light yellow paper
  music_theme: TODO
  description: TODO
  variants:
    - Notebook paper background
    - Engineering paper background
  concept_art: img/concept-art/paper

- name: Pen on Scrap Paper
  color_scheme: Black or dark blue ink on white paper
  music_theme: Gospel / churchy
  description: TODO
  variants:
    - Blue, black, or red ink for the grid and marks
    - Bank deposit slip background
    - Store receipt background

- name: Neon Lights
  color_scheme: luminescent orange, pink, blue
  music_theme: 80's electronic
  description: TODO
  concept_art: img/concept-art/neon

- name: Early Computer
  color_scheme: green or amber on black
  music_theme: 8-bit electronic
  description: TODO
  concept_art: img/concept-art/computer
  variants:
    - Green marks and grid
    - Amber marks and grid

- name: Sidewalk
  color_scheme: pastels including blue, yellow, and orange on gray
  music_theme: Hip Hob / R&B
  description: TODO
  concept_art: img/concept-art/sidewalk
  variants:
    - Grid and mark colors randomly picked from pastel palette

- name: Papyrus Paper and Fancy Calligraphy
  color_scheme: Black on faded tan
  music_theme: Something classical
  description: TODO


# TODO: here are some more environments to describe
# * Old Paper / Pencil
# * Cryon on paper
# * Cyber punk future thing / Neon
# * Old school computer
# * Back of receipt or deposit slip with pen
# * Actual console version (easter egg / debugging aid / works over ssh)
# * Shower door / bathroom mirror
# * iPhone app thing
# * Beach / sand
# * Side walk chalk
# * Chalkboard / black board
# * bathroom stall / scraped metal
#   - Every once in a while include some straining sound FX for some good
#     bathroom humor.
# * Playground spinney thing
# * Dirty car back window
# * Snow / frozen lake?
# * something to do with food
# * Light board - like those found in ships
# * Carved into rock or granet
# * Led grid / 16x4 LCD display
# * Microscope / scanning electron microscope
# * Notebook paper
# * Oldschool paper / fancy text with ink
# * Paint / masterpiece on canvas with oil paint
# * Tron inspired theme
# * OXO oscilloscope throwback theme
# * Laser cutter / lasers
# * metal / glass forge
# * Empty / test / debug level
# * Blueprint - this might work well as the theme used when making new environments.
# * Clone of James' 2004 Tic Tac Toe

